package com.sap.imdb.model;

public enum Genre
{
	COMEDY, ACTION, ROMANCE, THRILLER, TERROR, DRAMA, DOCUMENTARY, NOVEL, GORE, HISTORICAL, RACE, MARCIALART, FIGHT, POLICE, SATIRICAL, GANGSTER, HORROR, KAIJU, TESTEENEUM
}
